# Generated by Django 3.2.25 on 2024-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='null.jpg', upload_to='image')),
            ],
        ),
    ]
